# Generated by Django 3.1.3 on 2021-06-01 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EventCreator',
            fields=[
                ('eventName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('team', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('regno', models.CharField(max_length=10)),
                ('slot', models.CharField(max_length=8)),
                ('teamID', models.CharField(max_length=5)),
                ('eventName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FileCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('file', models.FileField(upload_to='data/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('regno', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=2)),
                ('tackle', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TempMember',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('regno', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Topscores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=4)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MathClubVitap.member')),
            ],
        ),
        migrations.CreateModel(
            name='TackleMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='tackle/%Y/%m/%d/')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MathClubVitap.member')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('type', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MathClubVitap.member')),
            ],
        ),
    ]
